/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_sunny_talker_push_ffmepg_FFmpegKit */

#ifndef _Included_net_sunny_talker_push_ffmepg_FFmpegKit
#define _Included_net_sunny_talker_push_ffmepg_FFmpegKit
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_sunny_talker_push_ffmepg_FFmpegKit
 * Method:    run
 * Signature: ([Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_net_sunny_talker_push_ffmepg_FFmpegKit_run
  (JNIEnv *, jclass, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
