/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_sunny_talker_push_ffmepg_FFmpegKit_KitInterface */

#ifndef _Included_net_sunny_talker_push_ffmepg_FFmpegKit_KitInterface
#define _Included_net_sunny_talker_push_ffmepg_FFmpegKit_KitInterface
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
